# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customer_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Заказы')),
                ('quantity', models.PositiveIntegerField(verbose_name='Колличество')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('done', models.BooleanField(default=True, verbose_name='Выполнен')),
                ('canceled', models.BooleanField(default=True, verbose_name='Отменен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Отзывы')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('caption', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('stars', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customer_avatar', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.ManyToManyField(to='shop.Product'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Customer'),
        ),
    ]
