# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170620_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customer_avatar', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Name'),
        ),
    ]
