# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170625_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Name'),
        ),
    ]
